name: aw
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  appwrite: ^11.0.1
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.2
  flutter_riverpod: ^2.4.9
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
